on:
  workflow_dispatch:

jobs:
  job_1:                  # runs first
    runs-on: ubuntu-latest
    steps:
      - run: "echo This is ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1            # run in parallel after job_1 finishes.
    steps:
      - run: "echo This is ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_1            # run in parallel after job_1 finishes.
    steps:
      - run: "echo This is ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_1,job_2]    # waits for both job_1 and job_2 to complete before running.
    steps:
      - run: "echo This is ${{ github.job }}"
