name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  ex-jop:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Hello!"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: list files
        run: ls -la
        
