on:
  push:              # on push to branches main/release & path src/**
    branches:
      - main
      - "release/**"
    path:
      - "src/**"
  
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout                       # clone the repository on the runner
        uses: actions/checkout@v4.2.2

      - name: Run tests
        run: npm test
  